"""automation/paths.py
공유 상태 파일 경로 상수 — automation_worker 및 신규 모듈이 공통으로 참조하는 leaf 모듈.
(리팩토링: automation_worker.py 모놀리스에서 분리. 순수 상수라 동작 변화 없음.)
"""
from project_paths import STATE, log_path

MODE_PATH = STATE / "mode_state.json"
TIMERS_PATH = STATE / "timers.json"
RECALC_STATE_PATH = STATE / "share_priority_recalc_state.json"

PRESENCE_PATH = STATE / "eunbi_presence.json"
DAY_CONTEXT_PATH = STATE / "day_context.json"
RANDOM_EVENT_POOL_PATH = STATE / "random_event_pool.json"
APPEARANCE_PATH = STATE / "eunbi_appearance_state.json"
WEEKEND_SCHEDULE_PATH = STATE / "weekend_schedule.json"
WEEKEND_PLAN_STATE_PATH = STATE / "weekend_plan_state.json"
WEATHER_PATH = STATE / "weather_context.json"
MEDIA_PATH = STATE / "media_watch_context.json"
PROACTIVE_PATH = STATE / "proactive_messages.json"
BRIEF_PATH = STATE / "daily_brief.json"
SHARE_CONTEXT_PATH = STATE / "share_event_context.json"
SHARE_PRIORITY_PATH = STATE / "share_priority_state.json"
SHARE_FLOW_PATH = STATE / "share_event_flow_state.json"
VOICE_SHARE_CONTEXT_PATH = STATE / "voice_share_event_context.json"
MEDIA_CHOICE_PATH = STATE / "media_choice_by_intent.json"
IMAGE_SETTINGS_PATH = STATE / "image_generation_settings.json"
IMAGE_GUARD_PATH = STATE / "image_generation_guard.json"
IMAGE_PROMPT_PLAN_PATH = STATE / "image_prompt_plan.json"
IMAGE_SHOT_HISTORY_PATH = STATE / "image_shot_history.json"
REINFORCEMENT_STATE_PATH = STATE / "user_preference_reinforcement.json"
DAILY_DIARY_STATE_PATH = STATE / "daily_diary_state.json"
MEMORY_DECAY_PATH = STATE / "memory_decay_state.json"
MOOD_RESIDUE_PATH = STATE / "mood_residue_state.json"
SIGNATURE_PHRASES_PATH = STATE / "signature_phrases.json"
AMBIENT_EVENTS_PATH = STATE / "ambient_life_events_state.json"
REPLY_VARIANCE_PATH = STATE / "reply_variance_state.json"
TASTE_FRICTION_PATH = STATE / "taste_friction_state.json"
PHRASE_REPETITION_GUARD_PATH = STATE / "phrase_repetition_guard_state.json"
DAY_SATISFACTION_PATH = STATE / "day_satisfaction_state.json"
RESPONSE_DECISION_LOG_PATH = log_path("response_decision_log.jsonl")
MOOD_TIMELINE_PATH = STATE / "mood_timeline.json"
PROACTIVE_PATTERN_REPORT_PATH = STATE / "proactive_pattern_report.json"
VOICE_FEEDBACK_LOG_PATH = log_path("voice_feedback_log.jsonl")
REPETITION_REPORT_PATH = STATE / "repetition_report.json"
RELATIONSHIP_PROGRESS_NOTES_PATH = STATE / "relationship_progress_notes.json"
CHAT_RUNTIME_SNAPSHOT_PATH = STATE / "chat_runtime_snapshot.json"
USER_CONVERSATION_STATE_PATH = STATE / "user_conversation_state.json"
COUNTERPART_STATE_MEMORY_PATH = STATE / "counterpart_state_memory.json"
CONVERSATION_PATTERN_STATE_PATH = STATE / "conversation_pattern_state.json"
CONVERSATION_PATTERN_CATALOG_PATH = STATE / "conversation_pattern_catalog.json"
EVENT_TRIGGER_PROMISES_PATH = STATE / "event_trigger_promises.json"
SELF_BUSY_STATE_PATH = STATE / "self_busy_state.json"
PENDING_INCOMING_PATH = STATE / "pending_incoming_messages.jsonl"
PENDING_PHOTO_PROMISE_PATH = STATE / "pending_photo_promise.json"
PENDING_ARRIVAL_PROMISE_PATH = STATE / "pending_arrival_promise.json"
PENDING_PROACTIVE_PHOTO_PATH = STATE / "pending_proactive_photo.json"
PROACTIVE_PHOTO_STATE_PATH = STATE / "proactive_photo_state.json"

__all__ = [n for n in dir() if n.endswith("_PATH") or n.endswith("_STATE_PATH")]
